### ISSUE TITLE
Model resuming

### ISSUE THREAD

**Issue by ethanwharris** [ecs-vlc/torchbearer#324]
Further to the discussion in #307, it would be nice for the resuming from checkpoint functionality to include some way of 'replaying' a model fit from the history. Since the model resuming is optional in the new API (can either resume or just load the model weights), I propose the following:

1. Change the run call to take 'max_epochs' instead of 'epochs', this should make no difference to those not resuming (or minor difference, could potentially offer both but it might be confusing)
2. Ammend the tqdm callback to print a kind of summary of the epochs until now if the initial epoch is not zero (i.e. when resuming). This might require storing more than just final metrics in history (although it would be nice to avoid storing running metrics in history, we could just take the value 10 times an epoch or something?)

The result of these two changes would be that: when resuming a model, the tqdm callback will 'catch you up' and you can have it simply 'replay' a fit call by loading in a model. An alternate option, would be to save all of the metrics, and have the fit call perform a callback run with the metrics. However, this seems a bit overkill as we would also need any other values from state that the callback uses. @kl2792 what are your thoughts on these? anything you would add?

**Comment by MattPainter01** [comment]
I like this idea. 

I do think that instead of Tqdm automatically replaying the previous epochs, we should instead give Trial a method that tells it to replay. If I've ran 500 epochs, I might not want my terminal to be filled with that much output. 

I also prefer just replaying epoch metrics and not run the callbacks, since the state_dict file needed to store all intermediate callback tensors/values might be very large.

**Comment by kl2792** [comment]
@ethanwharris This sounds great! I like the idea of the TQDM callback catching you up, since it's already handling other TQDM-related things. I agree with @MattPainter01 that it might be too computationally expensive to rerun all callbacks (esp. in the case of 100+ epochs) -- as you said, it could be better to save the TQDM bar info only for printing and final callback states for loading. And it does make sense that the replay should be optional in the case of large numbers of epochs.

Thank you for implementing this!
