### ISSUE TITLE
Running indefinitely?

### ISSUE THREAD

**Issue by ethanwharris** [ecs-vlc/torchbearer#400]
Currently there is no way to ask torchbearer to run until stopped. This would be useful for reinforcement learning where we don't know how long an episode will be.

**Comment by ethanwharris** [comment]
@MattPainter01 any ideas for how to do this? Possibly a 'train_until_stopped' method on Trial? Alternatively step count = -1 could trigger indefinite looping?

**Comment by MattPainter01** [comment]
Either of those seem fine, although I'd probably slightly lean towards steps = -1 myself. 

We'd just need to make sure we have some graceful way of stopping, not sure of how to do that outside of listening for a terminal input, which I'm not sure would work in an IDE like pycharm. If we did something like this though I might prefer train_until_stopped  since it would have this additional behaviour.

**Comment by ethanwharris** [comment]
To add:
for_inf_train_steps (and val and test)
- makes it run the train / val / test phase untill programatically stopped
with_inf_train_generator (and val and test, maybe a different name)
- makes the dataloader loop even if epoch is less than or grater than the length of the dataloader
